# ---------------------------------------------------------
# 1. Persistent Volume (PV): 物理的な保存場所の定義
# ---------------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # 【重要】過去のバックアップ設定に合わせて /data/minecraft を指定
    path: "/data/minecraft"
    type: DirectoryOrCreate # ディレクトリがなければ自動作成

---
# ---------------------------------------------------------
# 2. Persistent Volume Claim (PVC): アプリからの利用申請
# ---------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# ---------------------------------------------------------
# 3. Deployment: マインクラフト本体と監視サイドカー
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-bedrock
  labels:
    app: minecraft-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock
  # 【重要】デッドロック回避のため Recreate (一度停止してから再作成) を採用
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      containers:
        # --- Main Container: Minecraft Bedrock Server ---
        - name: minecraft
          image: itzg/minecraft-bedrock-server:latest
          tty: true
          stdin: true
          ports:
            - containerPort: 19132
              protocol: UDP
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: "survival"
            - name: DIFFICULTY
              value: "hard"
            # 満員エラー対策
            - name: MAX_PLAYERS
              value: "20"
            - name: SERVER_NAME
              value: "Tagomori-Server"
            # JST設定
            - name: TZ
              value: "Asia/Tokyo"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data

        # --- Sidecar Container: Exporter (mc-monitor) ---
        - name: exporter
          image: itzg/mc-monitor:latest
          command: ["/mc-monitor", "export", "-servers", "localhost:19132"]
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: TZ
              value: "Asia/Tokyo"

      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc

---
# ---------------------------------------------------------
# 4. Services: 外部公開用ポート定義
# ---------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-svc-game
spec:
  selector:
    app: minecraft-bedrock
  type: NodePort
  ports:
    - protocol: UDP
      port: 19132
      targetPort: 19132
      nodePort: 30000 # ゲーム用ポート

---
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-svc-metrics
spec:
  selector:
    app: minecraft-bedrock
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # 監視用ポート